Update docs for SquashFS images
NeonGeckoCom/neon-docs pull request #16
Opened 2023-08-02 21:46 UTC by NeonDaniel

# Description
Add note in skill installation to use config to ensure skills are re-installed after updates
Add description for the Device Updater Plugin and note root FS changes

# Issues

# Other Notes

2023-08-02 23:14 UTC, builderjer reviewed
The link to OSM community docs is no more. It has not really been updated in quite some time.

2023-08-05 00:36 UTC, NeonClary requested changes

2023-08-05 00:36 UTC, NeonClary commented on docs/neon_os/neon_os_updates.md
> +of updates. Operating System updates are managed by the
updates --> update

2023-08-05 00:36 UTC, NeonClary commented on docs/neon_os/neon_os_updates.md
> +that persist updates, here are some guidelines.
persist updates --> persist through updates

2023-08-05 00:36 UTC, NeonClary commented on docs/neon_os/using_neon_os.md
> +`Factory Settings` -> `Reset Device`. This removes any user settings, restores a
'Reset Device' --> 'Factory Reset'   (the button label is factory reset, not reset device)

2023-08-14 20:35 UTC, merged